# Generated by Django 6.0.5 on 2026-06-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Product Description'),
            preserve_default=False,
        ),
    ]
